local ServerStorage = game:GetService("ServerStorage")

local NPCLib = {
    ["Sex"] = {"Male","Female"},
    ["SkinTones"] = {
        Color3.fromRGB(255, 224, 189), -- Light
        Color3.fromRGB(255, 204, 153), -- Light Tan
        Color3.fromRGB(255, 153, 102), -- Tan
        Color3.fromRGB(255, 102, 51), -- Medium Tan
        Color3.fromRGB(204, 85, 0), -- Dark Tan
        Color3.fromRGB(153, 76, 0), -- Brown
        Color3.fromRGB(102, 51, 0), -- Dark Brown
        Color3.fromRGB(51, 25, 0), -- Darker Brown
    },
    ["FirstNames"] = {
        ["Male"] = {
            "Aaron",
            "Adam",
            "Alan",
            "Albert",
            "Alexander",
            "Andrew",
            "Anthony",
            "Arthur",
            "Austin",
            "Benjamin",
            "Billy",
            "Bobby",
            "Brandon",
            "Brian",
            "Bruce",
            "Bryan",
            "Caleb",
            "Carl",
            "Charles",
            "Christian",
            "Christopher",
            "Cole",
            "Connor",
            "Daniel",
            "David",
            "Derek",
            "Dennis",
            "Donald",
            "Douglas",
            "Dylan",
            "Edward",
            "Eric",
            "Ethan",
            "Eugene",
            "Frank",
            "Gabriel",
            "Gary",
            "George",
            "Gerald",
            "Gregory",
            "Harold",
            "Harry",
            "Henry",
            "Isaac",
            "Jack",
            "Jacob",
            "James",
            "Jason",
            "Jeffrey",
            "Jerry",
            "Jesse",
            "Joe",
            "John",
            "Johnny",
            "Jonathan",
            "Jordan",
            "Jose",
            "Joseph",
            "Joshua",
            "Juan",
            "Justin",
            "Keith",
            "Kenneth",
            "Kevin",
            "Kyle",
            "Larry",
            "Lawrence",
            "Liam",
            "Logan",
            "Louis",
            "Lucas",
            "Mark",
            "Matthew",
            "Michael",
            "Nathan",
            "Nick",
            "Nicholas",
            "Noah",
            "Owen",
            "Patrick",
            "Paul",
            "Peter",
            "Philip",
            "Ralph",
            "Randy",
            "Raymond",
            "Richard",
            "Robert",
            "Roger",
            "Ronald",
            "Roy",
            "Ryan",
            "Samuel",
            "Scott",
            "Sean",
            "Shane",
            "Stephen",
            "Steven",
            "Thomas",
            "Timothy",
            "Travis",
            "Tyler",
            "Victor",
            "Vincent",
            "Walter",
            "Wayne",
            "William",
            "Zachary",
        },
        ["Female"] = {
            "Abigail",
            "Alexis",
            "Alyssa",
            "Amanda",
            "Amber",
            "Amy",
            "Andrea",
            "Angela",
            "Anna",
            "Ashley",
            "Barbara",
            "Brittany",
            "Brooke",
            "Caitlin",
            "Candice",
            "Carla",
            "Carmen",
            "Caroline",
            "Carolyn",
            "Catherine",
            "Chelsea",
            "Charlotte",
            "Chloe",
            "Christina",
            "Cynthia",
            "Danielle",
            "Deborah",
            "Destiny",
            "Diana",
            "Donna",
            "Elizabeth",
            "Ella",
            "Emily",
            "Emma",
            "Erica",
            "Eva",
            "Faith",
            "Felicia",
            "Gabriella",
            "Grace",
            "Hailey",
            "Hannah",
            "Heather",
            "Holly",
            "Isabella",
            "Jacqueline",
            "Jade",
            "Jamie",
            "Jane",
            "Jasmine",
            "Jennifer",
            "Jessica",
            "Jillian",
            "Joan",
            "Jordan",
            "Julia",
            "Julie",
            "Kaitlyn",
            "Karen",
            "Katherine",
            "Kathleen",
            "Katie",
            "Kayla",
            "Kelly",
            "Kimberly",
            "Kristen",
            "Kristin",
            "Kylie",
            "Laura",
            "Lauren",
            "Leah",
            "Lillian",
            "Lily",
            "Linda",
            "Lisa",
            "Madeline",
            "Madison",
            "Maria",
            "Marissa",
            "Mary",
            "Megan",
            "Melanie",
            "Melissa",
            "Mia",
            "Michelle",
            "Molly",
            "Monica",
            "Morgan",
            "Nancy",
            "Natalie",
            "Nicole",
            "Olivia",
            "Paige",
            "Patricia",
            "Rachel",
            "Rebecca",
            "Samantha",
            "Sandra",
            "Sara",
            "Sarah",
            "Savannah",
            "Shannon",
            "Sophia",
            "Stephanie",
            "Susan",
            "Sydney",
            "Taylor",
            "Tiffany",
            "Vanessa",
            "Victoria",
        },
    },
    ["LastNames"] = {
        "Adams",
        "Allen",
        "Alvarez",
        "Anderson",
        "Bailey",
        "Baker",
        "Bennett",
        "Brooks",
        "Brown",
        "Campbell",
        "Carter",
        "Castillo",
        "Chavez",
        "Clark",
        "Collins",
        "Cook",
        "Cooper",
        "Cox",
        "Cruz",
        "Davis",
        "Diaz",
        "Edwards",
        "Evans",
        "Flores",
        "Foster",
        "Garcia",
        "Gomez",
        "Gonzalez",
        "Gray",
        "Green",
        "Gutierrez",
        "Hall",
        "Harris",
        "Hernandez",
        "Hill",
        "Howard",
        "Hughes",
        "Jackson",
        "James",
        "Johnson",
        "Jones",
        "Kelly",
        "Kim",
        "King",
        "Lee",
        "Lewis",
        "Lopez",
        "Long",
        "Martinez",
        "Mendoza",
        "Miller",
        "Mitchell",
        "Moore",
        "Morgan",
        "Morales",
        "Morris",
        "Murphy",
        "Myers",
        "Nelson",
        "Nguyen",
        "Ortiz",
        "Parker",
        "Patel",
        "Perez",
        "Peterson",
        "Phillips",
        "Price",
        "Ramirez",
        "Ramos",
        "Reed",
        "Reyes",
        "Richardson",
        "Rivera",
        "Roberts",
        "Robinson",
        "Rodriguez",
        "Rogers",
        "Ross",
        "Ruiz",
        "Russell",
        "Sanders",
        "Sanchez",
        "Scott",
        "Smith",
        "Stewart",
        "Taylor",
        "Thomas",
        "Thompson",
        "Torres",
        "Turner",
        "Walker",
        "Ward",
        "Watson",
        "White",
        "Williams",
        "Wilson",
        "Wright",
        "Wood",
        "Young",
        "Zuniga",
    },
    ["Roles"] = {
        "Farmer",
        "Miner",
        "Hunter",
        "Fisher",
        "Arms Dealer",
        "Mechanic",
        "Doctor",
        "Gas Attendant",
        "Store Clerk",
    },
    ["Clothing"] = {
        ["Farmer"] = {
            ["Outfits"] = {
                {["Top"] = "http://www.roblox.com/asset/?id=186045242",["Bottom"] = "http://www.roblox.com/asset/?id=200796058"},
                {["Top"] = "http://www.roblox.com/asset/?id=6537438567",["Bottom"] = "http://www.roblox.com/asset/?id=6537442061"},
                {["Top"] = "http://www.roblox.com/asset/?id=9393520979",["Bottom"] = "http://www.roblox.com/asset/?id=9393518309"},
                {["Top"] = "http://www.roblox.com/asset/?id=18863728432",["Bottom"] = "http://www.roblox.com/asset/?id=18863733241"},
            },
        },
        ["Miner"] = {
            ["Outfits"] = {
                {["Top"] = "http://www.roblox.com/asset/?id=2504907703",["Bottom"] = "http://www.roblox.com/asset/?id=2504927810"},
                {["Top"] = "http://www.roblox.com/asset/?id=9880993770",["Bottom"] = "http://www.roblox.com/asset/?id=9880997959"},
            },
        },
        ["Hunter"] = {
            ["Outfits"] = {
                {["Top"] = "http://www.roblox.com/asset/?id=1208507969",["Bottom"] = "http://www.roblox.com/asset/?id=1208508183"},
                {["Top"] = "http://www.roblox.com/asset/?id=9880993770",["Bottom"] = "http://www.roblox.com/asset/?id=9880997959"},
                {["Top"] = "http://www.roblox.com/asset/?id=436471722",["Bottom"] = "http://www.roblox.com/asset/?id=436471577"},
            },
        },
        ["Fisher"] = {
            ["Outfits"] = {
                {["Top"] = "http://www.roblox.com/asset/?id=11400925282",["Bottom"] = "http://www.roblox.com/asset/?id=11400932998"},
            },
        },
        ["Arms Dealer"] = {
            ["Outfits"] = {
                {["Top"] = "http://www.roblox.com/asset/?id=2008515828",["Bottom"] = "http://www.roblox.com/asset/?id=2008556212"},
            },
        },
        ["Mechanic"] = {
            ["Outfits"] = {
                {["Top"] = "http://www.roblox.com/asset/?id=2008691065",["Bottom"] = "http://www.roblox.com/asset/?id=2008689586"},
            },
        },
        ["Doctor"] = {
            ["Outfits"] = {
                {["Top"] = "http://www.roblox.com/asset/?id=367469643",["Bottom"] = "http://www.roblox.com/asset/?id=367469469"},
                {["Top"] = "http://www.roblox.com/asset/?id=4451628236",["Bottom"] = "http://www.roblox.com/asset/?id=4451627653"},
            },
        },
        ["Casual"] = {
            ["Outfits"] = {
                {["Top"] = "http://www.roblox.com/asset/?id=5050068424",["Bottom"] = "http://www.roblox.com/asset/?id=5050067024"},
                {["Top"] = "http://www.roblox.com/asset/?id=4451560899",["Bottom"] = "http://www.roblox.com/asset/?id=4451560088"},
                {["Top"] = "http://www.roblox.com/asset/?id=5570881928",["Bottom"] = "http://www.roblox.com/asset/?id=5570885364"},
                {["Top"] = "http://www.roblox.com/asset/?id=5772038087",["Bottom"] = "http://www.roblox.com/asset/?id=5772035689"},
                {["Top"] = "http://www.roblox.com/asset/?id=3607797409",["Bottom"] = "http://www.roblox.com/asset/?id=3607799011"},
            },
        },
    },
    ["Hair"] = {
        ["Male"] = {},
        ["Female"] = {},
    },
}

return NPCLib